# Environment that does not use a GPU
#  Installs packages needed for all features
name: jitterbug
channels:
  - defaults
  - conda-forge
  - pytorch
  - conda-forge/label/libint_dev
dependencies:
  - python==3.10.*

  # Standard data analysis tools
  - pandas==1.*
  - scipy==1.*
  - jupyterlab
  - matplotlib
  - pytest
  
  # Quantum chemistry
  - psi4==1.8.*

  # Use Conda PyTorch to avoid OpenMP disagreement with other libraries
  - pytorch==2.0.*
  - cpuonly

  - pip
  - pip:
    - -e ..[test]
