# Environment that does not use a GPU
#  Installs packages needed for all features
name: jitterbug
channels:
  - defaults
  - conda-forge
  - conda-forge/label/libint_dev
dependencies:
  - python==3.9.*

  # Standard data analysis tools
  - pandas==1.*
  - scipy==1.*
  - jupyterlab
  - matplotlib
  - pytest
  - scikit-learn
  
  # Quantum chemistry
  - psi4==1.8.*  # Remove for MacOS systems
  - mopac

  # Interatomic forcefields
  - dscribe==2.1.*

  # Use Conda PyTorch to avoid OpenMP disagreement with other libraries
  - pytorch==2.0.*=*cpu*

  - pip
  - pip:
    - git+https://gitlab.com/ase/ase.git  # Needed for MOPAC
    - gpytorch==1.11.*
    - -e ..[test]
