name: CI

on: [push, pull_request]

permissions:
  contents: read
  
defaults:
  run:
    shell: bash -el {0}  # Lets conda work

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3
    - name: Set up environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: envs/environment-cpu.yml
        activate-environment: test
        auto-activate-base: true
        auto-update-conda: false
        remove-profiles: true
        architecture: x64
        clean-patched-environment-file: true
        run-post: true
        use-mamba: true
        miniforge-version: latest
    - name: Install test dependencies
      run: |
        pip install -e .[test]
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 jitterbug tests
    - name: Test with pytest
      run: pytest --cov=jitterbug --timeout=300 tests
    - name: Coveralls
      run: |
        pip install coveralls
        coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
